version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nilnil
    - nlreturn
    - paralleltest
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    dupl:
      threshold: 1000
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G115
    mnd:
      ignored-files:
        - examples/.*
      ignored-functions:
        - context.WithTimeout
        - strconv.ParseComplex
    nestif:
      min-complexity: 9
    revive:
      rules:
        - name: blank-imports
          disabled: true
    wsl:
      strict-append: false
      allow-assign-and-call: false
      allow-trailing-comment: true
      allow-separated-leading-comment: true
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - perfsprint
        path: _test\.go
      - linters:
          - forbidigo
        path: internal\/cli\/.*\.go
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments
      - path: (.+)\.go$
        text: if statements should only be cuddled with assignments used in the if statement itself
      - path: (.+)\.go$
        text: assignments should only be cuddled with other assignments
      - path: (.+)\.go$
        text: declarations should never be cuddled
    paths:
      - apis
      - api
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - apis
      - api
      - third_party$
      - builtin$
      - examples$
