run:
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - mnd
    - depguard
    - funlen
    - containedctx
    - exhaustruct
    - testpackage
    - varnamelen
    - maintidx
    - err113
    - nlreturn
    - wrapcheck
    - tagliatelle
    - paralleltest
    - lll
    - contextcheck
    - gochecknoglobals
    - tagalign
    - nilnil
    - godot
    - godox
    - gci
    - gocognit
    - gocyclo
    - cyclop
    - ireturn
    - gofumpt
    - gochecknoinits

linters-settings:
  wsl:
    allow-assign-and-call: false
    strict-append: false
    allow-trailing-comment: true
    allow-cuddle-declarations: true
    allow-separated-leading-comment: true
  revive:
    rules:
      - name: blank-imports
        disabled: true
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 9
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 1000
  mnd:
    ignored-functions:
      - "context.WithTimeout"
      - "strconv.ParseComplex"
    ignored-files:
      - "examples/.*"
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G115

issues:
  exclude:
    - "if statements should only be cuddled with assignments" # from wsl
    - "if statements should only be cuddled with assignments used in the if statement itself" # from wsl
    - "assignments should only be cuddled with other assignments" # from wsl. false positive case: var a bool\nb := true
    - "declarations should never be cuddled" # from wsl
  exclude-rules:
    - path: _test\.go
      linters:
        - perfsprint
    - path: internal\/cli\/.*\.go
      linters:
        - forbidigo
  exclude-dirs:
    - apis
    - api
