version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alices
  - AnnotatedEventf
  - antfu
  - apierrors
  - apiextensions
  - apimachinery
  - appsv1
  - asciinema
  - ayaka
  - batchv1
  - cainjection_in_models
  - certmanager
  - clientcmd
  - clientgoscheme
  - clusterrole
  - clusterrolebinding
  - containedctx
  - corev1
  - crdkustomizecainjectionpatch
  - crdkustomizeresource
  - crdkustomizewebhookpatch
  - deepcopy
  - deletecollection
  - dupl
  - durationcheck
  - envtest
  - errcheck
  - errname
  - Eventf
  - exportloopref
  - finalizers
  - forcetypeassert
  - genericclioptions
  - genericiooptions
  - goarch
  - goconst
  - gocyclo
  - gofmt
  - goheader
  - goimports
  - gomega
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - healthz
  - iconify
  - ineffassign
  - intstr
  - kollama
  - krew
  - krew.googlecontainertools.github.com
  - kubebuilder
  - kubebuilder:subresource
  - kubectlollama
  - kustomization
  - kustomize
  - kustomizeconfig
  - manifestskustomizesamples
  - metav1
  - metricsserver
  - musttag
  - nakedret
  - nekomeowww
  - nestif
  - nodeport
  - nolebase
  - nolint
  - nolintlint
  - nosprintfhostport
  - octicon
  - OIDC
  - ollama
  - ollamav1
  - onsi
  - persistentvolumeclaims
  - persistentvolumes
  - pflag
  - prealloc
  - predeclared
  - printcolumn
  - readyz
  - rolebinding
  - samber
  - servicemonitor
  - statefulsets
  - staticcheck
  - storageclasses
  - subresource
  - tenv
  - testableexamples
  - unconvert
  - undeployed
  - unocss
  - unparam
  - utilruntime
  - vitepress
  - vueuse
  - webhookcainjection_patc
ignoreWords: []
import: []
